apiVersion: apps/v1
kind: Deployment
metadata:
  name: sm-phpmyadmin
  labels:
    app: sm-phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sm-phpmyadmin
  template:
    metadata:
      labels:
        app: sm-phpmyadmin
    spec:
      containers:
        - name: sm-phpmyadmin
          image: phpmyadmin/phpmyadmin
          ports:
            - containerPort: 80
          env:
            - name: PMA_HOST
              value: sm-mysql
            - name: PMA_PORT
              value: "3306"
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sm-mysql-secret
                  key: sm-mysql-root-pass
            - name: PMA_USER
              valueFrom:
                secretKeyRef:
                  name: sm-mysql-secret
                  key: sm-mysql-smuser
            - name: PMA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sm-mysql-secret
                  key: sm-mysql-smpass